export const PAGE_LINKS = {
  HOME: "/",
  CIPHER: "/cipher",
  CLOAK: "/cloak",
  BEACON: "/beacon",
  BEACON_DOCS: "/docs/beacon",
  BLOG: "/blog",
  RESEARCH: "/research",
  DOCS: "/docs",
  RELAYER: "/relayer",
  GITHUB: "https://github.com/Privacy-Protocol",
  TWITTER: "https://x.com/BuildOnPrivacy",
  TELEGRAM: "https://t.me/buildonprivacy",
  DISCORD: "https://discord.gg/aCmAGWaB",
  CIPHER_DOCS: "/docs/cipher",
  CLOAK_DOCS: "/docs/cloak",
  CONTACT: "/contact",
}
